name: Build VST3 Win7
on: [push, workflow_dispatch]
jobs:
  build-win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.77.2"
          targets: x86_64-pc-windows-msvc

      - name: Clean old index / lock
        run: |
          Remove-Item Cargo.lock -Force -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force $env:CARGO_HOME\registry\cache -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force $env:CARGO_HOME\registry\index -ErrorAction SilentlyContinue

      - name: Bundle
        run: cargo run -p xtask -- bundle gradient-knob-vst3 --release

      - uses: actions/upload-artifact@v4
        with:
          name: GradientKnob-VST3
          path: target/bundled/**/*.vst3